ALTER SESSION SET CONTAINER = XEPDB1;

-- =========================================================
-- UAT host 10 users
-- =========================================================
CREATE USER UAT10_MULEUSER IDENTIFIED BY "uat$#muleuser10";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT10_MULEUSER;
ALTER USER UAT10_MULEUSER QUOTA UNLIMITED ON USERS;

CREATE USER UAT10_TIBCOUSER IDENTIFIED BY "uat#$tibcouser10";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT10_TIBCOUSER;
ALTER USER UAT10_TIBCOUSER QUOTA UNLIMITED ON USERS;

CREATE USER UAT10_JAVAUSER IDENTIFIED BY "uat#$javauser10";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT10_JAVAUSER;
ALTER USER UAT10_JAVAUSER QUOTA UNLIMITED ON USERS;

-- =========================================================
-- UAT host 11 users
-- =========================================================
CREATE USER UAT11_MULEUSER IDENTIFIED BY "uat#$muleuser11";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT11_MULEUSER;
ALTER USER UAT11_MULEUSER QUOTA UNLIMITED ON USERS;

CREATE USER UAT11_TIBCOUSER IDENTIFIED BY "uat#$tibcouser11";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT11_TIBCOUSER;
ALTER USER UAT11_TIBCOUSER QUOTA UNLIMITED ON USERS;

CREATE USER UAT11_JAVAUSER IDENTIFIED BY "uat#$javauser11";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO UAT11_JAVAUSER;
ALTER USER UAT11_JAVAUSER QUOTA UNLIMITED ON USERS;

-- =========================================================
-- PROD host 20 users
-- =========================================================
CREATE USER PROD20_MULEUSER IDENTIFIED BY "prod$#muleuser20";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD20_MULEUSER;
ALTER USER PROD20_MULEUSER QUOTA UNLIMITED ON USERS;

CREATE USER PROD20_TIBCOUSER IDENTIFIED BY "prod#$tibcouser20";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD20_TIBCOUSER;
ALTER USER PROD20_TIBCOUSER QUOTA UNLIMITED ON USERS;

CREATE USER PROD20_JAVAUSER IDENTIFIED BY "prod#$javauser20";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD20_JAVAUSER;
ALTER USER PROD20_JAVAUSER QUOTA UNLIMITED ON USERS;

-- =========================================================
-- PROD host 21 users
-- =========================================================
CREATE USER PROD21_MULEUSER IDENTIFIED BY "prod$#muleuser21";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD21_MULEUSER;
ALTER USER PROD21_MULEUSER QUOTA UNLIMITED ON USERS;

CREATE USER PROD21_TIBCOUSER IDENTIFIED BY "prod$#tibcouser21";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD21_TIBCOUSER;
ALTER USER PROD21_TIBCOUSER QUOTA UNLIMITED ON USERS;

CREATE USER PROD21_JAVAUSER IDENTIFIED BY "prod#$javauser21";
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO PROD21_JAVAUSER;
ALTER USER PROD21_JAVAUSER QUOTA UNLIMITED ON USERS;

COMMIT;