format_version: 10

pipelines:
  MULE_LIQUIBASE_DB_MULTI_ENVS:
    group: mule-rtf-automation-pipeline-ops-prod
    label_template: '${COUNT}'
    lock_behavior: none
    display_order: -1

    secure_variables:
      UAT_172_25_0_10_MULEUSER_PASSWORD: 'AES:9GCOFM/1uXJ/kk2iNvcJIg==:bcZU5SGJuR7me2cZIh2ZXg=='
      UAT_172_25_0_10_TIBCOUSER_PASSWORD: 'AES:FsRIHJQR3zfokfzhTCUciQ==:6wzwF0Zqm36Z/Hq8x8iWrIXFb+EG/uRyJbcoArEO3Ck='
      UAT_172_25_0_10_JAVAUSER_PASSWORD: 'AES:0NtipUYusAc8t/Lc8DmXBg==:v8w5iQPkdROMqmEox9Otug=='
      UAT_172_25_0_11_MULEUSER_PASSWORD: 'AES:npDt9TtIVg0AHYtK26n1mA==:oWxpdJ4weEwqELfJqCUznQ=='
      UAT_172_25_0_11_TIBCOUSER_PASSWORD: 'AES:K0k5IUhzcZEa7X1F8V3VuQ==:atiOt+poytxvAujnaml7RmjbOxx2VS+HEX2qySArSLI='
      UAT_172_25_0_11_JAVAUSER_PASSWORD: 'AES:g5c9PWMDWjCMNTA/6CLvnw==:11501jV/M4QwRs3mrxahsA=='
      PROD_172_25_0_20_MULEUSER_PASSWORD: 'AES:vVSbooQhL/lKpflNIOUVJg==:wRMtFLeJDv7wJx440Fg9olNl+wW+Q0VbsQoznJ5nRb8='
      PROD_172_25_0_20_TIBCOUSER_PASSWORD: 'AES:y/vJ/u7tRCU9xQ/SX1zWrw==:B0l2CGnq0HU9y28jRO1YdwYCCc25mdvvutP70nm3wGc='
      PROD_172_25_0_20_JAVAUSER_PASSWORD: 'AES:qKI3uX8LNvQeSLQSRehGzg==:+vgVe8djWy9ssCKuLGPeFcoQZ6fwdlwv4nnW5QKcN4Y='
      PROD_172_25_0_21_MULEUSER_PASSWORD: 'AES:Up8sA39G8FPNdNb8c/BnvQ==:xUr7mXXbNHgGPySwLc0yQRIv7S9psjTcw8zOd7rWqww='
      PROD_172_25_0_21_TIBCOUSER_PASSWORD: 'AES:/U+mkR6hYhuGlujIywjBsw==:RwY/FYueqL2/jQqgckoCMh9NTohIkmHVl/Nzvsq5QEw='
      PROD_172_25_0_21_JAVAUSER_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
      ARTIFACTORY_USERNAME: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
      ARTIFACTORY_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
    environment_variables:
      ENVIRONMENT: UAT
      DATABASE_URL: jdbc:oracle:thin:@//10.5.20.213:1521/ORCLPDB1
      DB_USERNAME: muleuser
      OPERATION: update
      CHANGEREQUEST_ID: CH123982828
      ROLLBACK_TAG: ''

    materials:
      git-liquibase-pipeline:
        git: https://github.com/oooflair/LB_PIPELINE.git
        shallow_clone: false
        auto_update: true
        branch: main
    parameters:
      ENVIRONMENT: UAT
      DATABASE_URL: jdbc:oracle:thin:@//10.5.20.213:1521/ORCLPDB1
      DB_USERNAME: muleuser
      OPERATION: update
      CHANGEREQUEST_ID: CH123982828
      ROLLBACK_TAG: ''
    stages:
      - Liquibase_Preview_Validation:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          secure_variables:
            UAT_172_25_0_10_MULEUSER_PASSWORD: 'AES:9GCOFM/1uXJ/kk2iNvcJIg==:bcZU5SGJuR7me2cZIh2ZXg=='
            UAT_172_25_0_10_TIBCOUSER_PASSWORD: 'AES:FsRIHJQR3zfokfzhTCUciQ==:6wzwF0Zqm36Z/Hq8x8iWrIXFb+EG/uRyJbcoArEO3Ck='
            UAT_172_25_0_10_JAVAUSER_PASSWORD: 'AES:0NtipUYusAc8t/Lc8DmXBg==:v8w5iQPkdROMqmEox9Otug=='
            UAT_172_25_0_11_MULEUSER_PASSWORD: 'AES:npDt9TtIVg0AHYtK26n1mA==:oWxpdJ4weEwqELfJqCUznQ=='
            UAT_172_25_0_11_TIBCOUSER_PASSWORD: 'AES:K0k5IUhzcZEa7X1F8V3VuQ==:atiOt+poytxvAujnaml7RmjbOxx2VS+HEX2qySArSLI='
            UAT_172_25_0_11_JAVAUSER_PASSWORD: 'AES:g5c9PWMDWjCMNTA/6CLvnw==:11501jV/M4QwRs3mrxahsA=='
            PROD_172_25_0_20_MULEUSER_PASSWORD: 'AES:vVSbooQhL/lKpflNIOUVJg==:wRMtFLeJDv7wJx440Fg9olNl+wW+Q0VbsQoznJ5nRb8='
            PROD_172_25_0_20_TIBCOUSER_PASSWORD: 'AES:y/vJ/u7tRCU9xQ/SX1zWrw==:B0l2CGnq0HU9y28jRO1YdwYCCc25mdvvutP70nm3wGc='
            PROD_172_25_0_20_JAVAUSER_PASSWORD: 'AES:qKI3uX8LNvQeSLQSRehGzg==:+vgVe8djWy9ssCKuLGPeFcoQZ6fwdlwv4nnW5QKcN4Y='
            PROD_172_25_0_21_MULEUSER_PASSWORD: 'AES:Up8sA39G8FPNdNb8c/BnvQ==:xUr7mXXbNHgGPySwLc0yQRIv7S9psjTcw8zOd7rWqww='
            PROD_172_25_0_21_TIBCOUSER_PASSWORD: 'AES:/U+mkR6hYhuGlujIywjBsw==:RwY/FYueqL2/jQqgckoCMh9NTohIkmHVl/Nzvsq5QEw='
            PROD_172_25_0_21_JAVAUSER_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
            ARTIFACTORY_USERNAME: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
            ARTIFACTORY_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
          jobs:
            Inspect_SQL:
              timeout: 0
              secure_variables:
                UAT_172_25_0_10_MULEUSER_PASSWORD: 'AES:9GCOFM/1uXJ/kk2iNvcJIg==:bcZU5SGJuR7me2cZIh2ZXg=='
                UAT_172_25_0_10_TIBCOUSER_PASSWORD: 'AES:FsRIHJQR3zfokfzhTCUciQ==:6wzwF0Zqm36Z/Hq8x8iWrIXFb+EG/uRyJbcoArEO3Ck='
                UAT_172_25_0_10_JAVAUSER_PASSWORD: 'AES:0NtipUYusAc8t/Lc8DmXBg==:v8w5iQPkdROMqmEox9Otug=='
                UAT_172_25_0_11_MULEUSER_PASSWORD: 'AES:npDt9TtIVg0AHYtK26n1mA==:oWxpdJ4weEwqELfJqCUznQ=='
                UAT_172_25_0_11_TIBCOUSER_PASSWORD: 'AES:K0k5IUhzcZEa7X1F8V3VuQ==:atiOt+poytxvAujnaml7RmjbOxx2VS+HEX2qySArSLI='
                UAT_172_25_0_11_JAVAUSER_PASSWORD: 'AES:g5c9PWMDWjCMNTA/6CLvnw==:11501jV/M4QwRs3mrxahsA=='
                PROD_172_25_0_20_MULEUSER_PASSWORD: 'AES:vVSbooQhL/lKpflNIOUVJg==:wRMtFLeJDv7wJx440Fg9olNl+wW+Q0VbsQoznJ5nRb8='
                PROD_172_25_0_20_TIBCOUSER_PASSWORD: 'AES:y/vJ/u7tRCU9xQ/SX1zWrw==:B0l2CGnq0HU9y28jRO1YdwYCCc25mdvvutP70nm3wGc='
                PROD_172_25_0_20_JAVAUSER_PASSWORD: 'AES:qKI3uX8LNvQeSLQSRehGzg==:+vgVe8djWy9ssCKuLGPeFcoQZ6fwdlwv4nnW5QKcN4Y='
                PROD_172_25_0_21_MULEUSER_PASSWORD: 'AES:Up8sA39G8FPNdNb8c/BnvQ==:xUr7mXXbNHgGPySwLc0yQRIv7S9psjTcw8zOd7rWqww='
                PROD_172_25_0_21_TIBCOUSER_PASSWORD: 'AES:/U+mkR6hYhuGlujIywjBsw==:RwY/FYueqL2/jQqgckoCMh9NTohIkmHVl/Nzvsq5QEw='
                PROD_172_25_0_21_JAVAUSER_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
                ARTIFACTORY_USERNAME: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
                ARTIFACTORY_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
              #elastic_profile_id: mulesoftrtfuat_dind
              environment_variables:
                ENVIRONMENT: UAT
                DATABASE_URL: jdbc:oracle:thin:@//10.5.20.213:1521/ORCLPDB1
                DB_USERNAME: muleuser
                OPERATION: update
                CHANGEREQUEST_ID: CH123982828
                ROLLBACK_TAG: ''
              tasks:
                - exec:
                    working_directory: liquibase_operations_oracle_database/liquibase_scripts
                    command: sh
                    arguments:
                      - ./run-liquibase.sh
                      - dryrun

      - Liquibase_Execute:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          secure_variables:
            UAT_172_25_0_10_MULEUSER_PASSWORD: 'AES:9GCOFM/1uXJ/kk2iNvcJIg==:bcZU5SGJuR7me2cZIh2ZXg=='
            UAT_172_25_0_10_TIBCOUSER_PASSWORD: 'AES:FsRIHJQR3zfokfzhTCUciQ==:6wzwF0Zqm36Z/Hq8x8iWrIXFb+EG/uRyJbcoArEO3Ck='
            UAT_172_25_0_10_JAVAUSER_PASSWORD: 'AES:0NtipUYusAc8t/Lc8DmXBg==:v8w5iQPkdROMqmEox9Otug=='
            UAT_172_25_0_11_MULEUSER_PASSWORD: 'AES:npDt9TtIVg0AHYtK26n1mA==:oWxpdJ4weEwqELfJqCUznQ=='
            UAT_172_25_0_11_TIBCOUSER_PASSWORD: 'AES:K0k5IUhzcZEa7X1F8V3VuQ==:atiOt+poytxvAujnaml7RmjbOxx2VS+HEX2qySArSLI='
            UAT_172_25_0_11_JAVAUSER_PASSWORD: 'AES:g5c9PWMDWjCMNTA/6CLvnw==:11501jV/M4QwRs3mrxahsA=='
            PROD_172_25_0_20_MULEUSER_PASSWORD: 'AES:vVSbooQhL/lKpflNIOUVJg==:wRMtFLeJDv7wJx440Fg9olNl+wW+Q0VbsQoznJ5nRb8='
            PROD_172_25_0_20_TIBCOUSER_PASSWORD: 'AES:y/vJ/u7tRCU9xQ/SX1zWrw==:B0l2CGnq0HU9y28jRO1YdwYCCc25mdvvutP70nm3wGc='
            PROD_172_25_0_20_JAVAUSER_PASSWORD: 'AES:qKI3uX8LNvQeSLQSRehGzg==:+vgVe8djWy9ssCKuLGPeFcoQZ6fwdlwv4nnW5QKcN4Y='
            PROD_172_25_0_21_MULEUSER_PASSWORD: 'AES:Up8sA39G8FPNdNb8c/BnvQ==:xUr7mXXbNHgGPySwLc0yQRIv7S9psjTcw8zOd7rWqww='
            PROD_172_25_0_21_TIBCOUSER_PASSWORD: 'AES:/U+mkR6hYhuGlujIywjBsw==:RwY/FYueqL2/jQqgckoCMh9NTohIkmHVl/Nzvsq5QEw='
            PROD_172_25_0_21_JAVAUSER_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
            ARTIFACTORY_USERNAME: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
            ARTIFACTORY_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
          jobs:
            Deploy_Changes:
              timeout: 0
              secure_variables:
                UAT_172_25_0_10_MULEUSER_PASSWORD: 'AES:9GCOFM/1uXJ/kk2iNvcJIg==:bcZU5SGJuR7me2cZIh2ZXg=='
                UAT_172_25_0_10_TIBCOUSER_PASSWORD: 'AES:FsRIHJQR3zfokfzhTCUciQ==:6wzwF0Zqm36Z/Hq8x8iWrIXFb+EG/uRyJbcoArEO3Ck='
                UAT_172_25_0_10_JAVAUSER_PASSWORD: 'AES:0NtipUYusAc8t/Lc8DmXBg==:v8w5iQPkdROMqmEox9Otug=='
                UAT_172_25_0_11_MULEUSER_PASSWORD: 'AES:npDt9TtIVg0AHYtK26n1mA==:oWxpdJ4weEwqELfJqCUznQ=='
                UAT_172_25_0_11_TIBCOUSER_PASSWORD: 'AES:K0k5IUhzcZEa7X1F8V3VuQ==:atiOt+poytxvAujnaml7RmjbOxx2VS+HEX2qySArSLI='
                UAT_172_25_0_11_JAVAUSER_PASSWORD: 'AES:g5c9PWMDWjCMNTA/6CLvnw==:11501jV/M4QwRs3mrxahsA=='
                PROD_172_25_0_20_MULEUSER_PASSWORD: 'AES:vVSbooQhL/lKpflNIOUVJg==:wRMtFLeJDv7wJx440Fg9olNl+wW+Q0VbsQoznJ5nRb8='
                PROD_172_25_0_20_TIBCOUSER_PASSWORD: 'AES:y/vJ/u7tRCU9xQ/SX1zWrw==:B0l2CGnq0HU9y28jRO1YdwYCCc25mdvvutP70nm3wGc='
                PROD_172_25_0_20_JAVAUSER_PASSWORD: 'AES:qKI3uX8LNvQeSLQSRehGzg==:+vgVe8djWy9ssCKuLGPeFcoQZ6fwdlwv4nnW5QKcN4Y='
                PROD_172_25_0_21_MULEUSER_PASSWORD: 'AES:Up8sA39G8FPNdNb8c/BnvQ==:xUr7mXXbNHgGPySwLc0yQRIv7S9psjTcw8zOd7rWqww='
                PROD_172_25_0_21_TIBCOUSER_PASSWORD: 'AES:/U+mkR6hYhuGlujIywjBsw==:RwY/FYueqL2/jQqgckoCMh9NTohIkmHVl/Nzvsq5QEw='
                PROD_172_25_0_21_JAVAUSER_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
                ARTIFACTORY_USERNAME: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
                ARTIFACTORY_PASSWORD: 'AES:lvY24GmQrO7/mLTTtHG5rA==:+UhJvc/h1XphIBPIcjL0xLzTDSgP6+RL3gzvhUAmNYo='
              #elastic_profile_id: mulesoftrtfuat_dind
              environment_variables:
                ENVIRONMENT: UAT
                DATABASE_URL: jdbc:oracle:thin:@//10.5.20.213:1521/ORCLPDB1
                DB_USERNAME: muleuser
                OPERATION: update
                CHANGEREQUEST_ID: CH123982828
                ROLLBACK_TAG: ''
              tasks:
                - exec:
                    working_directory: liquibase_operations_oracle_database/liquibase_scripts
                    command: sh
                    arguments:
                      - ./run-liquibase.sh
                      - execute